### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by cgrigis** [mlbench/mlbench-core#62] opened 2020-04-15 16:43 UTC
It looks like several "stale" branches (either already merged or inactive) exist in the repository.
Unless there is a good reason to keep them around, they should probably be deleted, which will remove clutter and improve clarity of the ongoing development activities.

**Comment by giorgiosav** [comment] 2020-04-17 10:52
We could each tick the branches that we know are still active, then delete the others.

- [ ] Add-aggregation-by-model
- [ ] Fix-CI
- [ ] RNN-Language-translation
- [ ] Refactoring
- [ ] Transformer-Language-translation
- [ ] add-centralized-adam
- [ ] dependabot/pip/tensorflow-1.15.2
- [ ] develop
- [ ] dist_tf
- [ ] feature/compute-official-results
- [ ] feature/get_optimizer
- [ ] feature/tf-dataloader
- [ ] feature/train-valid-separation
- [ ] linear-model
- [ ] master
- [ ] mlbench-cli
- [ ] modify_lr_schedulers
- [ ] release/1.0.0
- [ ] remember-user-input
- [ ] rnn-controlflow
- [ ] sparsified_sgd

**Comment by Panaetius** [comment] 2020-04-17 15:02
If we get rid of TF then all the tf branches are not needed anymore.

I'll change the github setting to automatically delete branches when they're merged.

**Comment by martinjaggi** [comment] 2020-04-17 15:54
we'd still like to have the code which reproduces the TF results. but it
would maybe have to be rewriten a bit since they have in newer versions
also improved data parallel (hopefully without param server)

**Closed** 2020-06-08 12:50 UTC
